=== wafaamuhammad123/XML-labs/Day2/task1/employees.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<!ELEMENT city (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone
	type (home | mobile | work) #REQUIRED
>
<!ELEMENT region (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT address (street, buildingNumber, city, region, country)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT employee (phone+, address)>
<!ATTLIST employee
	name (wafaa | menna) #REQUIRED
	email CDATA #REQUIRED
>
<!ELEMENT employees (employee+)>
<!ELEMENT buildingNumber (#PCDATA)>

=== wafaamuhammad123/XML-labs/Day2/task1/emloyee.xml
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
	<employee name="wafaa" email="wafaa@gmail.com">
		<phone type="work">01274865283</phone>
		<phone type="mobile">01273673137</phone>
		<address>
			<street>main st.</street>
			<buildingNumber>24</buildingNumber>
			<city>alexandria</city>
			<region>Agamy</region>
			<country>Egypt</country>
		</address>
	</employee>
	<employee name="menna" email="menna@gmail.com">
		<phone type="home">01279876493</phone>
		<phone type="mobile">01224105773</phone>
		<address>
			<street>mostafa kamel.</street>
			<buildingNumber>14</buildingNumber>
			<city>stanly</city>
			<region>alexandria</region>
			<country>Egypt</country>
		</address>
	</employee>
</employees>
